version: "2"
services:
  game-auth:
    container_name: game-auth
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - '/opt/mongodb/data:/opt/mongodb/data'
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - game-auth
