version: "2"
services:
  game-auth:
    container_name: game-auth-container
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    command: mongod --auth
    ports:
      - "27017:27017"
